services:
  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_password
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
