@baseUrl = http://localhost:3333/api
@accessToken = {{createSession.response.body.access_token}}
@equipmentId = {{creatEquipment.response.body.id}}

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Example",
  "email": "example@example.com",
  "password": "password"
}

###

# @name createSession
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "password"
}

###

# @name creatEquipment
POST {{baseUrl}}/equipments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Excaator Sensor",
  "description": "Heavy duty excavator"
}

###

# @name getEquipments
GET {{baseUrl}}/equipments
Authorization: Bearer {{accessToken}}

###

# @name createMeasurement
POST {{baseUrl}}/measurements
Content-Type: application/json

{
  "timestamp": "2025-09-06T00:00:00.000Z",
  "value": 80,
  "equipmentId": "{{equipmentId}}"
}

###

# @name getMeasurementsByEquipmentId
GET {{baseUrl}}/measurements/{{equipmentId}}?timeFrame=1m

###