@baseUrl = http://localhost:3333/api
@token = {{createSession.response.body.token}}
@equipmentId = {{creatEquipment.response.body.equipment.id}}

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Example",
  "email": "example123@example.com",
  "password": "password"
}

###

# @name createSession
POST {{baseUrl}}/users/session
Content-Type: application/json

{
  "email": "example123@example.com",
  "password": "password"
}

###

# @name creatEquipment
POST {{baseUrl}}/equipments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Excaator Sensor",
  "description": "Heavy duty excavator"
}

###

# @name getEquipments
GET {{baseUrl}}/equipments
Authorization: Bearer {{token}}

###

# @name createMeasurement
POST {{baseUrl}}/measurements/{{equipmentId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "timestamp": "2025-09-06T00:00:00.000Z",
  "value": 80
}

###

# @name getMeasurementsByEquipmentId
GET {{baseUrl}}/measurements/EQ-12496/average
Authorization: Bearer {{token}}

###