@baseUrl = http://localhost:3000/api
@accessToken = {{createSession.response.body.access_token}}

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Example",
  "email": "example@example.com",
  "password": "password"
}

###

# @name createSession
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "password"
}

###
# @name creatEquipment
POST {{baseUrl}}/equipments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Calculadora",
  "description": "Calculadora científica"
}
